name: 简单易懂的现代魔法
description: 我们不生产代码，我们只是github的搬运工
meta_description: "简单易懂的现代魔法 - 我们不生产代码，我们只是github的搬运工"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://lhc-clover.github.io'
google_analytics: 'UA-XXXXXXXX-X'
plugins: [jekyll-paginate]
future: true

# Details for the RSS feed generator
url:            'lhc-clover.github.io'
author:         'CC'
